Add_layer
panorama-softwares/homerun pull request #19
Opened 2023-08-28 14:52 UTC by Jayas121

added responsive and color over image

2023-08-28 16:00 UTC, gitgenjutsu commented on pages/branding.tsx
> +  <header className="h-96 w-100  bg-bluer text-center bg-blue bg-blend-multiply" style={{
bg-bluer - remove this

2023-08-28 16:01 UTC, gitgenjutsu commented on pages/mobile.tsx
> +          <header className="h-96 w-100  bg-bluer text-center bg-blue bg-blend-multiply" style={{
remove - bg-bluer

2023-08-28 16:02 UTC, gitgenjutsu commented on tailwind.config.js
> +          "2xl": "1536px",
"2xl" - should not be in strings

2023-08-28 16:03 UTC, gitgenjutsu requested changes
Solve comments

2023-08-29 07:17 UTC, Jayas121 commented
corrected my mistake

2023-08-29 07:18 UTC, merged