Completed footer component
panorama-softwares/homerun pull request #3
Opened 2023-08-16 10:12 UTC by Jayas121

Created Footer and added about page

2023-08-16 11:03 UTC, gitgenjutsu commented on components/Footer/index.tsx
> +// import { useState } from "react";
Please removed commented code, if no use

2023-08-16 11:04 UTC, gitgenjutsu commented on components/Footer/index.tsx
> +
Do indentation of code

2023-08-16 11:05 UTC, gitgenjutsu commented on pages/_app.tsx
> +        <Layout>
Do indentation in all files

2023-08-16 11:06 UTC, gitgenjutsu commented on styles/header.css
> +/*.More{
Removed unused code from all files, if not needed

2023-08-16 11:09 UTC, gitgenjutsu requested changes
Please solve conflicts and comments

2023-08-17 16:29 UTC, Jayas121 commented
updated footer

2023-08-17 16:30 UTC, Jayas121 commented
updated Footer

2023-08-18 12:13 UTC, merged